<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

|**Term**|**Brief description**|
|:--|:--|
|Subsetting|The action of selecting|
|Indexing|Selecting one element|
|Slicing|Selecting a range of elements|
|Masking|Selecting *using the notion of 'True' and 'False'*|

# Exercise 2

In [2]:
import numpy as np

In [3]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [12]:
x = np_array_2d[:10, 0].astype(int)
x

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [13]:
x % 2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

In [22]:
x % 2 == 1

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [25]:
my_mask = np_array_2d[x % 2 == 1]
my_mask

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U11')

In [26]:
my_mask[:, 1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')