<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [1]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [3]:
py_super_names = ['Black Widow', 'Iron Man', 'Doctor Strange']
py_real_names = ['Natasha Romanoff', 'Tony Stark', 'Stephen Strange']

In [4]:
np_super_names = np.array(['Black Widow', 'Iron Man', 'Doctor Strange'])
np_real_names = np.array(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [6]:
superhero_info = {
    'Natasha Romanoff': 'Black Widow',
    'Tony Stark': 'Iron Man',
    'Stephen Strange': 'Doctor Strange'
}
#dictionaries use :
#can hold both information in one, unlike lists or array that need two

## 1.2 Accessing data from a list (or array)

In [8]:
py_real_names[0]

'Natasha Romanoff'

In [9]:
py_super_names[0]

'Black Widow'

In [10]:
py_super_names[1]

'Iron Man'

In [11]:
py_super_names[2]

'Doctor Strange'

In [13]:
py_super_names[-1] #allow python to count from the back

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [14]:
superhero_info['Natasha Romanoff']

'Black Widow'

In [15]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [16]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [17]:
superhero_info = [['Natasha Romanoff', 'Black Widow'],
                  ['Tony Stark', 'Iron Man'],
                  ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [3]:
import numpy as np

In [4]:
py_list_2d = [[1, 'A'], [2, 'B'], [3, 'C'], [4, 'D'],
              [5, 'E'], [6, 'F'], [7, 'G'], [8, 'H'],
              [9, 'I'], [10, 'J']]
np_array_2d =np.array(py_list_2d) #creating new NumPy array by reusing the python list

In [7]:
len(py_list_2d)

10

In [8]:
len(np_array_2d)

10

In [9]:
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type

In [11]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [12]:
py_list
np_array

array(['1', '1.5', 'A'], dtype='<U32')

In [13]:
py_list

[1, 1.5, 'A']

## 2.3 Adding a number

In [14]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [15]:
np_array + 10

array([11, 12, 13, 14, 15])

In [16]:
py_list + 10

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [17]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_list_1 = np.array(py_list_1)
np_list_2 = np.array(py_list_2)

In [18]:
py_list_1 + py_list_2 #combine the two lists

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [19]:
np_list_1 + np_list_2 #add the values in the list together to form 1

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [21]:
py_list = [1, 2, 3, 4, 5]
np_list = np.array(py_list)

In [22]:
py_list * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [23]:
np_list * 2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [25]:
py_list = [1, 2, 3, 4, 5]
np_list = np.array(py_list)

In [26]:
py_list ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [27]:
np_list ** 2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [28]:
py_list =[1, 2, 3, 4, 5]
np_list = np.array(py_list)

In [29]:
py_list == 3

False

In [30]:
np_list == 3

array([False, False,  True, False, False])

In [31]:
np_list > 3

array([False, False, False,  True,  True])

In [32]:
py_list > 3

TypeError: '>' not supported between instances of 'list' and 'int'

## 2.8 Mathematics

In [33]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [34]:
sum(py_list)

15

In [35]:
np_array.sum()

15

In [36]:
max(py_list)

5

In [38]:
np_array.max()

5

In [39]:
min(py_list)

1

In [40]:
np_array.min()

1

In [41]:
np_array.mean()

3.0

In [42]:
np_array.std()

1.4142135623730951

In [43]:
py_list.sum()

AttributeError: 'list' object has no attribute 'sum'

## Footnotes