<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [2]:
import numpy as np

In [3]:
py_list = ["a1", "b2", "c3", "d4", "e5",
           "f6", "g7", "h8", "i9", "j10"]
np_array = np.array(py_list)

In [4]:
x = np_array

In [5]:
x[0]

'a1'

In [7]:
x[0:3]

array(['a1', 'b2', 'c3'], dtype='<U3')

In [8]:
x[1:6]

array(['b2', 'c3', 'd4', 'e5', 'f6'], dtype='<U3')

In [11]:
x[1:6:2] #in steps of two

array(['b2', 'd4', 'f6'], dtype='<U3')

In [12]:
x[5:]

array(['f6', 'g7', 'h8', 'i9', 'j10'], dtype='<U3')

In [13]:
x[0:5]

array(['a1', 'b2', 'c3', 'd4', 'e5'], dtype='<U3')

In [18]:
x[5:2:-1] #reverse 5-2 elemets from index 5

array(['f6', 'e5', 'd4'], dtype='<U3')

In [17]:
x[::-1] #reverse the list

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

## 1.2 Arrays only | Subsetting by masking

In [19]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [20]:
my_mask = np_array > 3

In [21]:
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [23]:
np_array[my_mask] #only show true answers

array([ 4,  5,  6,  7,  8,  9, 10])

In [25]:
np_array[np_array > 3] #do not need to create a new variable

array([ 4,  5,  6,  7,  8,  9, 10])

In [27]:
np_array[~(np_array > 3)] #'~' means not

array([1, 2, 3])

In [29]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means and

array([4, 5, 6, 7])

In [33]:
np_array[(np_array < 3) | (np_array > 8)] #'|' means or

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [34]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [37]:
py_list_2d[3]


[4, 'D']

In [38]:
np_array_2d[3]

array(['4', 'D'], dtype='<U11')

In [39]:
py_list_2d[3][0]

4

In [40]:
np_array_2d[3, 0]

'4'

In [41]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [42]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [43]:
py_list_2d[:3][0]

[1, 'A']

In [44]:
np_array_2d[:3][0]

array(['1', 'A'], dtype='<U11')

In [45]:
py_list_2d[3:6][0]

[4, 'D']

In [47]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U11')

In [48]:
np_array_2d[:6, 0]

array(['1', '2', '3', '4', '5', '6'], dtype='<U11')

## 1.4 Growing lists

# Some loose ends

## 1.5 Tuples

## 1.6 Be VERY careful when copying

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes